name: Deploy to Salesforce Org

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install --global @salesforce/cli

    - name: Authenticate to Salesforce
      env:
        SF_ACCESS_TOKEN: ${{ secrets.SF_ACCESS_TOKEN }}
        SF_ORG_INSTANCE_URL: ${{ secrets.SF_ORG_INSTANCE_URL }}
        SF_REFRESH_TOKEN: ${{ secrets.SF_REFRESH_TOKEN }}
        SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
        SF_CLIENT_SECRET: ${{ secrets.SF_CLIENT_SECRET }}
      run: |
        # Format the auth URL for sf CLI
        echo "force://${{ secrets.SF_CLIENT_ID }}:${{ secrets.SF_CLIENT_SECRET }}:${{ secrets.SF_REFRESH_TOKEN }}@${{ secrets.SF_ORG_INSTANCE_URL }}" > auth_url.txt
        
        # Authenticate using the sf CLI
        sf login url --sfdx-url-file auth_url.txt --set-default

    - name: Deploy to Salesforce Org
      run: sf project deploy start --source-path force-app --target-org default
