name: Deploy to Salesforce Org

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install --global sfdx-cli

    - name: Authenticate to Salesforce
      env:
        SF_ACCESS_TOKEN: ${{ secrets.SF_ACCESS_TOKEN }}
        SF_ORG_INSTANCE_URL: ${{ secrets.SF_ORG_INSTANCE_URL }}
        SF_REFRESH_TOKEN: ${{ secrets.SF_REFRESH_TOKEN }}
      run: |
        echo "force://${{ secrets.SF_CLIENT_ID }}:${{ secrets.SF_CLIENT_SECRET }}:${{ secrets.SF_REFRESH_TOKEN }}@${{ secrets.SF_ORG_INSTANCE_URL }}" > auth_url.txt
        sfdx auth:sfdx-url:store --sfdx-url-file auth_url.txt --alias default --set-default

    - name: Deploy to Salesforce Org
      run: sfdx force:source:deploy -p force-app --target-org default
