name: Deploy to Salesforce Org

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Salesforce CLII
      run: npm install --global sfdx-cli

    - name: Authenticate to Salesforce
      env:
        SFDX_CONSUMER_KEY: ${{ secrets.SFDX_CONSUMER_KEY }}
        SFDX_CONSUMER_SECRET: ${{ secrets.SFDX_CONSUMER_SECRET }}
        SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        GH_PAT: ${{ secrets.GH_PAT }}  # Include the GitHub PAT here if needed for GitHub API calls
      run: |
        sfdx auth:oauth:login --setdefaultdevhubusername --instanceurl $SFDX_AUTH_URL --consumerkey $SFDX_CONSUMER_KEY --consumersecret $SFDX_CONSUMER_SECRET

    - name: Deploy to Salesforce Org
      run: sfdx force:source:deploy -p force-app
