name: Deploy to Salesforce Org

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install --global sfdx-cli

    - name: Authenticate to Salesforce
      env:
        SFDX_CONSUMER_KEY: ${{ secrets.SFDX_CONSUMER_KEY }}
        SFDX_CONSUMER_SECRET: ${{ secrets.SFDX_CONSUMER_SECRET }}
        SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        SFDX_ALIAS: 'my-org-alias'  # Set an alias for the authenticated org
      run: |
        echo $SFDX_AUTH_URL > auth_url.txt
        sfdx auth:sfdxurl:store --setalias $SFDX_ALIAS --sfdxurlfile auth_url.txt --setdefaultusername

    - name: Deploy to Salesforce Org
      run: sfdx force:source:deploy -p force-app --target-org $SFDX_ALIAS
