name: Deploy to Salesforce Org

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install --global sfdx-cli

    - name: Authenticate to Salesforce
      env:
        SFDX_ACCESS_TOKEN: ${{ secrets.SFDX_ACCESS_TOKEN }}
        SFDX_INSTANCE_URL: ${{ secrets.SFDX_INSTANCE_URL }}
      run: |
        echo "force://$SFDX_ACCESS_TOKEN:@$SFDX_INSTANCE_URL" > auth_url.txt
        sfdx auth:sfdxurl:store --sfdxurlfile auth_url.txt --setdefaultusername

    - name: Deploy to Salesforce Org
      run: sfdx force:source:deploy -p force-app --target-org default
